import Head from "next/head";
import { AboutProps } from "../interfaces/about.interface";
import React from "react";
import About from "../components/About";

export default function Home() {
	const [about, setAbout] = React.useState<AboutProps[]>([]);

	React.useEffect(() => {
		async function fetchData() {
			const response = await fetch("/api/about");
			const data = await response.json();
			setAbout(data.data);
		}
		fetchData();
	}, []);
	const data = [...about][0];
	console.log(data?.name);
	return (
		<>
			<Head>
				<title>{data?.name}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="container">
				<About data={data} />

			</div>
		</>
	);
}
